
services:
  db:
    image: mariadb:latest
    restart: always
    env_file:
      - .env
    environment:
      MARIADB_ROOT_PASSWORD: ${ROOT_PASSWORD}
      MARIADB_DATABASE: ${DB_NAME}
      MARIADB_USER: ${DB_USER}
      MARIADB_PASSWORD: ${DB_PASSWORD}
    volumes:
      - mariadb_data:/var/lib/mysql
    ports:
      - "3306:3306"

  web:
    build: .
    container_name: site_sushi
    restart: always
    ports:
      - "8080:5000"
    depends_on:
      - db
    env_file:
      - .env
    environment:
      FLASK_APP: monApp.app:app
      FLASK_ENV: production


volumes:
  mariadb_data: