DROP TABLE IF EXISTS RESTAURATRICE;
drop table if EXISTS CONTENIR_P;
drop table if EXISTS CONTENIR_F;
drop table if EXISTS COMPOSER;
drop table if EXISTS FORMULE;
drop table if EXISTS PLAT;
drop table if EXISTS TYPE_PLAT;
drop table if EXISTS RESERVATION;
drop table if EXISTS CLIENT;